version: "3.9"

services:
  base:
    container_name: base
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=test_secret
      - MYSQL_DATABASE=test
    restart: always
    volumes:
      - /home/base/mysql:/var/lib/mysql

  app:
    container_name: app
    build: ./api/
    depends_on:
      - base
    environment:
      - SQL_CONNECTION_URL=mysql://root:test_secret@base:3306/test
    expose:
      - 8080
    labels:
      - "traefik.enable=true"


      - "traefik.http.routers.app-http.entrypoints=http"
      - "traefik.http.routers.app-http.rule=Host(`coin.it-apostol.ru`)"
      - "traefik.http.routers.app-http.middlewares=redirect-https"
      - "traefik.http.routers.app-http.service=app"
      - "traefik.http.routers.app.rule=Host(`coin.it-apostol.ru`)"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app-docs.rule=Host(`coin.it-apostol.ru`) && PathPrefix(`/docs`, `/redoc`, `/openapi.json`)"
      - "traefik.http.routers.app-docs.entrypoints=https"
      - "traefik.http.routers.app-docs.tls=true"
      - "traefik.http.routers.app-docs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app-docs.middlewares=auth"
      - "traefik.http.routers.app-docs.service=app"
      - "traefik.http.services.app-docs.loadbalancer.server.port=8080"
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.4.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  filebeat:
    container_name: filebeat
    image: elastic/filebeat:8.4.0
    volumes:
      - /home/traefik/logs:/logs/traefik
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/data:/data
  kibana:
    container_name: kibana
    image: kibana:8.4.0
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana-http.entrypoints=http"
      - "traefik.http.routers.kibana-http.rule=Host(`kibana.it-apostol.ru`)"
      - "traefik.http.routers.kibana-http.service=kibana"
      - "traefik.http.routers.kibana-http.middlewares=auth@docker"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/portiner/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-http.entrypoints=http"
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.it-apostol.ru`)"
      - "traefik.http.routers.portainer-http.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  traefik:
    container_name: traefik
    build: ./traefik/
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml:ro
      - /home/traefik/auth.htpasswd:/auth.htpasswd:ro
      - /home/traefik/acme.json:/acme.json
      - /home/traefik/logs:/logs/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.it-apostol.ru`)"
      - "traefik.http.routers.traefik.middlewares=auth@docker"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth.htpasswd"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"

