version: "3.9"

services:
  base:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test_secret
      - MYSQL_DATABASE=test
    restart: always

  app:
    build: ./api/
    depends_on:
      - base
    environment:
      - SQL_CONNECTION_URL=mysql://root:test_secret@base:3306/test
    command: "python3.10 -m uvicorn main:app --port 8080 --host 0.0.0.0"
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`coin.it-apostol.ru`)"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsEncrypt"
      - "traefik.http.services.traefik-traefik.loadbalancer.server.port=888"
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
    command: --configfile=/home/traefik/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/home/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.it-apostol.ru`)"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$dd1Ad8v4$$x.JNsDB42EWADIekeAvHR1"
      - "traefik.http.routers.traefik.middlewares=auth@docker"
      