version: "3.9"

services:
  base:
    container_name: base
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test_secret
      - MYSQL_DATABASE=test
    restart: always

  app:
    container_name: app
    build: ./api/
    depends_on:
      - base
    environment:
      - SQL_CONNECTION_URL=mysql://root:test_secret@base:3306/test
    command: "python3.10 -m uvicorn main:app --port 8080 --host 0.0.0.0"
    expose:
      - 8080
    labels:
      - "traefik.enable=true"


      - "traefik.http.routers.app-http.entrypoints=http"
      - "traefik.http.routers.app-http.rule=Host(`coin.it-apostol.ru`)"
      - "traefik.http.routers.app-http.middlewares=redirect-https"
      - "traefik.http.routers.app-http.service=app"
      - "traefik.http.routers.app.rule=Host(`coin.it-apostol.ru`)"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app-docs.rule=Host(`coin.it-apostol.ru`) && PathPrefix(`/docs`, `/redoc`, `/openapi.json`)"
      - "traefik.http.routers.app-docs.entrypoints=https"
      - "traefik.http.routers.app-docs.tls=true"
      - "traefik.http.routers.app-docs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app-docs.middlewares=auth"
      - "traefik.http.routers.app-docs.service=app"
      - "traefik.http.services.app-docs.loadbalancer.server.port=8080"
  traefik:
    container_name: traefik
    build: ./traefik/
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/auth.htpasswd:/auth.htpasswd:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.it-apostol.ru`)"
      - "traefik.http.routers.traefik.middlewares=auth@docker"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth.htpasswd"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"

