providers:
  docker: true

api:
  dashboard: true
  
entrypoints:
  http:
    address: ":80"
  https:
    address: ":443"
log:
  level: DEBUG
certificatesResolvers:
  letsencrypt:
    acme:
      email: svetovoyvv@yandex.ru
      storage: acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http

